<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($_title = $block->getCurrentCategory()->getName()): ?>
	<?php if ($_imageUrl = $block->getCurrentCategory()->getImageUrl()): ?>
    <h1 class="category-title" style="display: none;">
        <?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_title, 'title') ?>
    </h1>
	<?php else: ?>
	<h1 class="category-title no-image">
        <?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_title, 'title') ?>
    </h1>
	<?php endif; ?>
<?php endif; ?>