<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php 
	$showWishlist = true;
	$showCompare = true;
?>

<?php if (($_products = $block->getProductCollection()) && $_products->getSize()): ?>
    <div class="block widget block-new-products-images">
        <div class="block-title">
            <strong><?= /* @escapeNotVerified */ __('New Products') ?></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $block->getNameInLayout(); ?>
            <ol id="widget-new-products-<?= /* @escapeNotVerified */ $suffix ?>" class="product-items product-items-images hp-new-prod">
                <?php foreach ($_products->getItems() as $_product): ?>
                    <li class="product-item">
                        <a class="product-item-photo" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"
                           title="<?= /* @escapeNotVerified */ $block->stripTags($_product->getName(), null, true) ?>">
                            <?php /* new_products_images_only_widget */ ?>
                            <?= $block->getImage($_product, 'new_products_images_names_only_widget')->toHtml() ?>
                        </a>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"
                                   title="<?= /* @escapeNotVerified */ $block->stripTags($_product->getName(), null, true) ?>)" class="product-item-link">
                                    <?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= /* @escapeNotVerified */ $block->getProductPriceHtml($_product, '-widget-new-' . $suffix) ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript" xml="space">
    require([
        'jquery',
        'slick'
    ], function ($) {
        jQuery(document).ready(function () {
            jQuery(".hp-new-prod").slick({
                lazyload: 'progressive',
        arrows: true,
        dots: false,
        slidesToShow: 5,
        slidesToScroll: 5,
        autoplay: false,
        autoplaySpeed: 5000,
        responsive: [
        	{
        		breakpoint: 1024,
        		settings: {
        			slidesToShow: 4,
        			slidesToScroll: 4,
        		}
        	},
        	{
        		breakpoint: 768,
        		settings: {
        			slidesToShow: 3,
        			slidesToScroll: 3,
        		}
        	},
        	{
        		breakpoint: 480,
        		settings: {
        			slidesToShow: 2,
        			slidesToScroll: 2,
        		}
        	}
        ]
            });
        });
    });
</script>