<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */
?>
<a href="#"
   class="action towishlist"
   title="<?= $block->escapeHtml(__('Add to Wish List')) ?>"
   aria-label="<?= $block->escapeHtml(__('Add to Wish List')) ?>"
   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'  
   data-action="add-to-wishlist" >
    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
</a>
<a href="#"
   class="action tocompare"
   title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
   aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
   data-post='<?= /* @escapeNotVerified */ $block->getCompareHelper()->getPostDataParams($block->getProduct()) ?>'
   role="button">
    <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
</a>