<?php
/**
 * Copying wishlist and modifiying code from trend.phtml and compare.phtml
 */
?>
<a href="#"
   class="action towishlist"
   title="<?= $block->escapeHtml(__('Add to Wish List')) ?>"
   aria-label="<?= $block->escapeHtml(__('Add to Wish List')) ?>"
   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'  
   data-action="add-to-wishlist" >
    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
</a>