<?php
/**
 * Magespider Facebook Chat Plugin
 */
/** @var $block \Magespider\FbChatModule\Block\FacebookMessenger **/
$fbChatModuleHelperData = $this->helper('Magespider\FbChatModule\Helper\Data');
?>
<!-- Facebook Messenger -->
<?php if ($fbChatModuleHelperData->getFacebookMessengerStatus()): ?>
<script>
    (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/<?= $block->getLocate(); ?>/sdk/xfbml.customerchat.js';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>
<!-- Your customer chat code -->
<?= $fbChatModuleHelperData->getFacebookMessengerChatCode(); ?>
<?php endif; ?>
<!-- End Facebook Messenger -->